# Generated by Django 5.1.2 on 2025-12-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('datos_json', models.JSONField()),
                ('imagen_base64', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
            ],
            options={
                'verbose_name': 'Evento Pendiente',
                'verbose_name_plural': 'Eventos Pendientes',
            },
        ),
    ]
