# Generated by Django 5.1.2 on 2025-12-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_editable', models.BooleanField(default=True)),
                ('apellido_editable', models.BooleanField(default=True)),
                ('telefono_editable', models.BooleanField(default=True)),
                ('fecha_nacimiento_editable', models.BooleanField(default=True)),
                ('intereses_editable', models.BooleanField(default=True)),
                ('email_editable', models.BooleanField(default=True)),
            ],
        ),
    ]