# Generated by Django 5.1.2 on 2025-12-15 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_eventopendiente'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=32, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('telefono_autorizado', models.CharField(blank=True, max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_whatsapp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Código WhatsApp',
                'verbose_name_plural': 'Códigos WhatsApp',
                'ordering': ['-creado_en'],
            },
        ),
    ]
