# Generated by Django 5.1.2 on 2025-12-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_evento_imagen_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='intereses',
            field=models.ManyToManyField(blank=True, related_name='interesados', to='api.categevento'),
        ),
    ]
