# Generated by Django 5.1.2 on 2025-12-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_configuracionperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='asistio',
            field=models.BooleanField(default=False),
        ),
    ]
