# Generated by Django 5.1.2 on 2025-12-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_inscripcion_asistio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
