# Generated by Django 5.1.2 on 2025-12-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_codigowhatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigowhatsapp',
            name='telefono_autorizado',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
