# Generated by Django 5.1.2 on 2025-12-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_codigowhatsapp_telefono_autorizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='datos_completos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='origen',
            field=models.CharField(choices=[('web', 'Panel Web'), ('whatsapp', 'WhatsApp')], default='web', max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
