# Generated by Django 5.1.2 on 2025-12-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_nacionalidad_to_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionperfil',
            name='primer_apellido_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionperfil',
            name='segundo_apellido_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
