# Generated by Django 5.1.2 on 2025-12-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_evento_datos_completos_evento_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False),
        ),
    ]
